openapi: 3.0.0
info:
  title: BETRIX Platform API
  version: 1.0.0
  description: API documentation for BETRIX Platform

servers:
  - url: https://betrix-platform.vercel.app
    description: Production server
  - url: http://localhost:3000
    description: Local development

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

    CanaryEnableRequest:
      type: object
      required:
        - model
      properties:
        model:
          type: string
          description: The model to enable
        clients:
          type: array
          items:
            type: string
          description: List of client IDs to enable the model for
        canaryCount:
          type: integer
          minimum: 1
          default: 2
          description: Number of random clients to select if no specific clients provided
        apply:
          type: boolean
          default: false
          description: Whether to actually apply changes or do a dry run

    MetricsResponse:
      type: object
      properties:
        errorRate:
          type: number
          format: float
        latencyMs:
          type: object
          properties:
            p95:
              type: number
            p99:
              type: number
        quotaUsage:
          type: number
          format: float

paths:
  /api/admin/canary/enable:
    post:
      summary: Enable a model for specific clients in canary mode
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CanaryEnableRequest'
      responses:
        '200':
          description: Model enabled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  changes:
                    type: array
                    items:
                      type: object
                      properties:
                        clientId:
                          type: string
                        model:
                          type: string
                        status:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Invalid API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'